### ISSUE TITLE
Wrong command to run: python scripts/data.py

### ISSUE THREAD

**Issue by fenghaolin** [datasets/s-and-p-500#4]
This is probably a typo. The right one should be
`python scripts/process.py`

After running this, I got something strange, though.

> Traceback (most recent call last):
>   File "scripts/process.py", line 74, in <module>
>     process()
>   File "scripts/process.py", line 70, in process
>     extract()
>   File "scripts/process.py", line 17, in extract
>     rows, metadata = xls.parse(open(fp))
>   File "E:\Programs\Anaconda\lib\site-packages\dataconverters\xls.py", line 32, in parse
>     table_set = xlsclass(stream, **kwargs)
>   File "E:\Programs\Anaconda\lib\site-packages\messytables\excel.py", line 77, in **init**
>     self.workbook = get_workbook()
>   File "E:\Programs\Anaconda\lib\site-packages\messytables\excel.py", line 50, in get_workbook
>     raise ReadError("Can't read Excel file: %r" % value, traceback)
> messytables.error.ReadError: ('Can\'t read Excel file: XLRDError("Unsupported format, or corrupt file: Expected BOF record; found \'\\xd0\\xcf\\x11\\xe0\\xa1\\xb1\'",)', <traceback object at 0x00000000038303C8>)

I think it is probably something related to the dataconverters I installed. But I installed it through the command:
`pip install dataconverters`
And I also installed messytables already.
I don't know what's wrong with that. Anybody also has similar problem? Thanks.

**Comment by anuveyatsu** [comment]
this issue should be invalid now as we have updated the scripts https://github.com/datasets/s-and-p-500/tree/main/scripts
